spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path:
  security:
    user:
      name: test
      password: yml
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 7000

logging:
  level:
    tacos: WARN

